//APP ACTION TYPES
export const NAVIGATE_APP = 'NAVIGATE_APP';
export const FETCH_APP_NUMBERS = 'FETCH_APP_NUMBERS';
export const SWAP_NUMBER_USAGE_VALUE = 'SWAP_NUMBER_USAGE_VALUE';

//USER ACTION TYPES
export const FETCH_SESSION_DATA = 'FETCH_SESSION_DATA';
